services:
  - type: web
    name: resume-screening
    env: python
     buildCommand: |
      pip install -r requirements.txt
      bash install_spacy_model.sh
    startCommand: gunicorn app:app
    plan: free
